version: "3.8"

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: fiap_user
      POSTGRES_PASSWORD: fiap_pass
      POSTGRES_DB: fiap_db
      TZ: Europe/Amsterdam     
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - fiap_net

  fiap_api:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://fiap_user:fiap_pass@db:5432/fiap_db
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    networks:
      - fiap_net

  fiap_scheduler:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://fiap_user:fiap_pass@db:5432/fiap_db
    command: ["python", "-m", "captura.scheduler"]
    networks:
      - fiap_net

volumes:
  db_data:

networks:
  fiap_net: